contact_import_def = {
    "C_SFDCContactID": "{{Contact.Field(C_SFDCContactID)}}",
    "C_Company": "{{Contact.Field(C_Company)}}",
    "C_SFDCAccountID": "{{Contact.Field(C_SFDCAccountID)}}",
    "C_City": "{{Contact.Field(C_City)}}",
    "C_Country": "{{Contact.Field(C_Country)}}",
    "C_EmailAddress": "{{Contact.Field(C_EmailAddress)}}",
    "C_SAP_Field_of_Work1": "{{Contact.Field(C_SAP_Field_of_Work1)}}",
    "C_FirstName": "{{Contact.Field(C_FirstName)}}",
    "C_LastName": "{{Contact.Field(C_LastName)}}",
    "C_Title": "{{Contact.Field(C_Title)}}",
    "C_MobilePhone": "{{Contact.Field(C_MobilePhone)}}",
    "C_SAP_Dealer_ID1": "{{Contact.Field(C_SAP_Dealer_ID1)}}",
    "C_BusPhone": "{{Contact.Field(C_BusPhone)}}",
    "C_SAP___Is_Plannja_Dealer1": "{{Contact.Field(C_SAP___Is_Plannja_Dealer1)}}",
    "C_SAP_Contact_Status1": "{{Contact.Field(C_SAP_Contact_Status1)}}",
    "C_Zip_Postal": "{{Contact.Field(C_Zip_Postal)}}"
}

account_import_def = {
    "M_SFDCAccountID": "{{Account.Field(M_SFDCAccountID)}}",
    "M_Address1": "{{Account.Field(M_Address1)}}",
    "M_SAP_BC_ABC_Classification1": "{{Account.Field(M_SAP_BC_ABC_Classification1)}}",
    "M_City": "{{Account.Field(M_City)}}",
    "M_Country": "{{Account.Field(M_Country)}}",
    "M_SAP_Dealer_Department1": "{{Account.Field(M_SAP_Dealer_Department1)}}",
    "M_SAP_Dealer_Name1": "{{Account.Field(M_SAP_Dealer_Name1)}}",
    "M_CompanyName": "{{Account.Field(M_CompanyName)}}",
    "M_SAP_Dealer_ID1": "{{Account.Field(M_SAP_Dealer_ID1)}}",
    "M_SAP_RC_Customer_Segment1": "{{Account.Field(M_SAP_RC_Customer_Segment1)}}",
    "M_SAP_Account_Role1": "{{Account.Field(M_SAP_Account_Role1)}}",
    "M_SAP_RR_ABC_Classification1": "{{Account.Field(M_SAP_RR_ABC_Classification1)}}",
    "M_SAP_RR_Tactical_Classification1": "{{Account.Field(M_SAP_RR_Tactical_Classification1)}}",
    "M_SAP_Account_Status1": "{{Account.Field(M_SAP_Account_Status1)}}",
    "M_Zip_Postal": "{{Account.Field(M_Zip_Postal)}}"
}

lead_import_def = {
    "C_SAP_Lead_ID1": "{{Contact.Field(C_SAP_Lead_ID1)}}",
    "C_SFDC___Lead_Record_Type_ID1": "{{Contact.Field(C_SFDC___Lead_Record_Type_ID1)}}",
    "C_SFDC___Lead_Name1": "{{Contact.Field(C_SFDC___Lead_Name1)}}",
    "C_SAP_Lead_Status1": "{{Contact.Field(C_SAP_Lead_Status1)}}",
    "C_SFDC_Dealer_Owner_ID1": "{{Contact.Field(C_SFDC_Dealer_Owner_ID1)}}",
    "C_Company": "{{Contact.Field(C_Company)}}",
    "C_Address1": "{{Contact.Field(C_Address1)}}",
    "C_City": "{{Contact.Field(C_City)}}",
    "C_Zip_Postal": "{{Contact.Field(C_Zip_Postal)}}",
    "C_State_Prov": "{{Contact.Field(C_State_Prov)}}",
    "C_Country": "{{Contact.Field(C_Country)}}",
    "C_EmailAddress": "{{Contact.Field(C_EmailAddress)}}",
    "C_FirstName": "{{Contact.Field(C_FirstName)}}",
    "C_LastName": "{{Contact.Field(C_LastName)}}",
    "C_Title": "{{Contact.Field(C_Title)}}",
    "C_MobilePhone": "{{Contact.Field(C_MobilePhone)}}",
    "C_Description1": "{{Contact.Field(C_Description1)}}",
    "C_SAP_Field_of_Work1": "{{Contact.Field(C_SAP_Field_of_Work1)}}",
    "C_SAP_B2B_Product_Group1": "{{Contact.Field(C_SAP_B2B_Product_Group1)}}",
    "C_SFDC___Dealer_Source1": "{{Contact.Field(C_SFDC___Dealer_Source1)}}",
    "C_SAP_Lead_Campaign_Value1": "{{Contact.Field(C_SAP_Lead_Campaign_Value1)}}",
    "C_SFDC___Roofing_lead_category1": "{{Contact.Field(C_SFDC___Roofing_lead_category1)}}",
    "C_SAP_Related_Roofing_Installation1": "{{Contact.Field(C_SAP_Related_Roofing_Installation1)}}",
    "C_SAP_Related_Roofing_Profile1": "{{Contact.Field(C_SAP_Related_Roofing_Profile1)}}",
    "C_SAP_Related_Roofing_RWS1": "{{Contact.Field(C_SAP_Related_Roofing_RWS1)}}",
    "C_SAP_Related_Roofing_Safety1": "{{Contact.Field(C_SAP_Related_Roofing_Safety1)}}",
    "C_SAP_Related_Roofing_Accessories1": "{{Contact.Field(C_SAP_Related_Roofing_Accessories1)}}",
    "C_SAP_Related_Roofing_Solar1": "{{Contact.Field(C_SAP_Related_Roofing_Solar1)}}",
    "C_SAP_Attachment_I1": "{{Contact.Field(C_SAP_Attachment_I1)}}",
    "C_SAP_Attachment_II1": "{{Contact.Field(C_SAP_Attachment_II1)}}",
    "C_SAP_Attachment_III1": "{{Contact.Field(C_SAP_Attachment_III1)}}",
    "C_SAP_Attachment_IV1": "{{Contact.Field(C_SAP_Attachment_IV1)}}",
    "C_SAP_Attachment_V1": "{{Contact.Field(C_SAP_Attachment_V1)}}",
    "C_SFDC___Created_To_Kata_Time1": "{{Contact.Field(C_SFDC___Created_To_Kata_Time1)}}",
    "C_Meeting_Date_for_email1": "{{Contact.Field(C_Meeting_Date_for_email1)}}",
    "C_Meeting_time_for_email1": "{{Contact.Field(C_Meeting_time_for_email1)}}",
    "C_SAP_UTM_Medium_Original1": "{{Contact.Field(C_SAP_UTM_Medium_Original1)}}",
    "C_SAP_UTM_Source_Original1": "{{Contact.Field(C_SAP_UTM_Source_Original1)}}",
    "C_SAP_UTM_Medium_Recent1": "{{Contact.Field(C_SAP_UTM_Medium_Recent1)}}",
    "C_SAP_UTM_Source_Recent1": "{{Contact.Field(C_SAP_UTM_Source_Recent1)}}",
    "C_SFDC_Roof_Doctor_Question_Category1": "{{Contact.Field(C_SFDC_Roof_Doctor_Question_Category1)}}"
}
